### ISSUE TITLE
重置刷新时间失败

### ISSUE THREAD

**Issue by buqian123** [xunichanghuan/mimotion#11]
![image](https://user-images.githubusercontent.com/22126477/130936299-d0513986-c63e-4112-b2b9-43bfd5645b59.png)
什么原因呢

**Comment by buqian123** [comment]
![image](https://user-images.githubusercontent.com/22126477/131255422-ab87bf4c-e3d2-4a96-acfa-46282cfbf211.png)
麻了，该怎么弄

**Comment by kurtn2005** [comment]
> ![image](https://user-images.githubusercontent.com/22126477/131255422-ab87bf4c-e3d2-4a96-acfa-46282cfbf211.png)
> 麻了，该怎么弄

git_pwd你配置做了，仔细看作者的说明。

**Comment by buqian123** [comment]
配置了的

**Comment by matocool** [comment]
我也是128 代码报错         全部都是按照作者的说明输入的


![image](https://user-images.githubusercontent.com/83129369/132177594-def8c3ec-39fb-40e8-9966-8c5d5d07a15c.png)

**Comment by kurtn2005** [comment]
> 我也是128 代码报错 全部都是按照作者的说明输入的
> 
> ![image](https://user-images.githubusercontent.com/83129369/132177594-def8c3ec-39fb-40e8-9966-8c5d5d07a15c.png)

不都说了吗，别用作者的git地址，用你自己的。

**Comment by matocool** [comment]
> ![image](https://user-images.githubusercontent.com/22126477/131255422-ab87bf4c-e3d2-4a96-acfa-46282cfbf211.png)
> 麻了，该怎么弄

成功了吗

**Comment by buqian123** [comment]
没有，可能是理解错了

**Comment by matocool** [comment]
![image](https://user-images.githubusercontent.com/83129369/132284728-a1e40c52-b52f-416f-b237-b26bf7e99040.png)


我昨天是报错 128  ，但是测试账号看了下，居然刷步数成功。今天修改地址为自己的，报错代码变成1了。

**Comment by matocool** [comment]
> 没有，可能是理解错了

git config --global user.name "xunichanghuan"
          git config --global user.email "zhpjake@vip.qq.com"
          git add .
          git commit -m '重置下次刷新时间'
          git remote set-url origin http://xunichanghuan:${git_pwd}@github.com/zailushang2008/mimotion.git
          git push

这一段代码，我发现你把git config --global user.name "xunichanghuan"      git config --global user.email "zhpjake@vip.qq.com"
这两个账户以及邮箱改成你自己的了。。。这是错的，我看别人成功的人都是默认的。。。

**Comment by matocool** [comment]
> > 我也是128 代码报错 全部都是按照作者的说明输入的
> > ![image](https://user-images.githubusercontent.com/83129369/132177594-def8c3ec-39fb-40e8-9966-8c5d5d07a15c.png)
> 
> 不都说了吗，别用作者的git地址，用你自己的。

我改了，用自己的变成错误代码1

**Comment by buqian123** [comment]
![图片](https://user-image.githubusercontent.com/22126477/132320367-b5b3fcd2-fafb-4339-a2a3-ed7ead2ec827.png)
x修改这一段为自己的就成功了

**Comment by buqian123** [comment]
![图片](https://user-images.githubusercontent.com/22126477/132320594-3e100bec-e5d4-4090-9316-e7fe4a208bfc.png)
