### ISSUE TITLE
作者请进。。。这个问题到底啥情况~~

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion#15]
首先，我打开了议题，参考以前的案例。

三个老哥都说程序可以刷成功，但是都会报错。

![image](https://user-images.githubusercontent.com/83129369/132285065-f6db3360-3d72-4e63-9958-a3a4fce1fd84.png)

################################################################################################
################################################################################################
################################################################################################
################################################################################################

然后我去查看他们修改的代码，以及action

三位老哥的 action 均报错         Error: Process completed with exit code 1.

https://github.com/delete222/mimotion/runs/3529472230?check_suite_focus=true

https://github.com/zailushang2008/mimotion/runs/3529460072?check_suite_focus=true

https://github.com/qiuhaiwei2020/mimotion/runs/3529410765?check_suite_focus=true

################################################################################################
################################################################################################
################################################################################################
################################################################################################

然后就是他们的所有工作流程都有问题。。。但是似乎都是可以同步成功。

![image](https://user-images.githubusercontent.com/83129369/132285450-8ea50afe-33b5-417f-8ab7-0c5e1b77c105.png)
![image](https://user-images.githubusercontent.com/83129369/132285466-89ce8e1d-44cf-4fed-958e-88770cdf8639.png)
![image](https://user-images.githubusercontent.com/83129369/132285475-d0d1e50f-e507-4ac1-afba-8b71fb21bf2a.png)

**Comment by kurtn2005** [comment]
从你提供的三个人的日志看，前两个是第二步出错了，也就是修改下一次运行时间的脚本报了exit 1，所以步数修改成功了。第三个应该是企业微信配置错了导致token有问题。

**Comment by kurtn2005** [comment]
我看了一下的rum.yml
git remote set-url origin http://xunichanghuan:${git_pwd}@github.com/matocool/mimotion.git
为什么还用作者的用户名啊？这肯定不行啊。你的把rum里面全换成自己的才行。

**Comment by matocool** [comment]
> 我看了一下的rum.yml
> git remote set-url origin [http://xunichanghuan:${git_pwd}@github.com/matocool/mimotion.git](http://xunichanghuan:$%7Bgit_pwd%7D@github.com/matocool/mimotion.git)
> 为什么还用作者的用户名啊？肯定这不行啊。你的把rum里面全是自己的才行。

嗯嗯，谢谢提示。我再改改。把run检查了一次能改成自己的全部改成自己了的。

话说作者自己也有报错。。
代码也是1

![image](https://user-images.githubusercontent.com/83129369/132314767-a7f4eedb-a6ee-48a4-8d05-2f12325e56fe.png)

**Comment by buqian123** [comment]
![图片](https://user-images.githubusercontent.com/22126477/132320267-9d1b314f-ef28-4de3-b714-0e2a2aaa725a.png)
只修改这一段就能成功

**Comment by matocool** [comment]
> ![图片](https://user-images.githubusercontent.com/22126477/132320267-9d1b314f-ef28-4de3-b714-0e2a2aaa725a.png)
> 只修改这一段就能成功

谢谢哥们~我去试试

**Comment by matocool** [comment]
> ![图片](https://user-images.githubusercontent.com/22126477/132320267-9d1b314f-ef28-4de3-b714-0e2a2aaa725a.png)
> 只修改这一段就能成功

哥们我看了下你的，，好像 运行也是报错1

**Comment by buqian123** [comment]
![图片](https://user-images.githubusercontent.com/22126477/132323345-952a1bec-b5c2-4111-94f1-4b1dbb8d1f87.png)
![图片](https://user-images.githubusercontent.com/22126477/132323417-2ab15ffc-6403-46e1-a9b4-a9c8e3f7e53f.png)
道理是那么个道理

**Comment by matocool** [comment]
> ![图片](https://user-images.githubusercontent.com/22126477/132323345-952a1bec-b5c2-4111-94f1-4b1dbb8d1f87.png)
> ![图片](https://user-images.githubusercontent.com/22126477/132323417-2ab15ffc-6403-46e1-a9b4-a9c8e3f7e53f.png)
> 道理是那么个道理

哥们 你这是 mi-sport.git  我不是耶 我去改改试试

**Comment by buqian123** [comment]
那是我git地址。。。你自己写你自己的

**Comment by matocool** [comment]
> 那是我git地址。。。你自己写你自己的

- name: 重置刷新时间
        run: |
          zsh random_cron.sh
          git_pwd='${{ secrets.GIT_PWD }}'
          git config --global user.name "matocool"
          git config --global user.email "matocool@foxmail.com"
          git add .
          git commit -m '重置下次刷新时间'
          git remote set-url origin http://xunichanghuan:${git_pwd}@github.com/matocool/mimotion.git
          git push

哥们我这样应该没错了吧

**Comment by buqian123** [comment]
git remote set-url origin http://xunichanghuan:${git_pwd}@github.com/matocool/mimotion.git

**Comment by buqian123** [comment]
对了

**Comment by matocool** [comment]
> 对了

谢谢哥们，我去跑起来试试~~

**Comment by matocool** [comment]
> 对了

成功了，谢谢哥们。。。但是好奇怪，，我之前明明改为正确的地址。。。但是却是错误。。。

![image](https://user-images.githubusercontent.com/83129369/132326168-4a89d57b-bc60-4276-ad63-9adf487f27ab.png)


![image](https://user-images.githubusercontent.com/83129369/132326008-8e5cd59e-ec1c-476f-930a-56ac0316a731.png)

**Comment by matocool** [comment]
> 我看了一下的rum.yml
> git remote set-url origin [http://xunichanghuan:${git_pwd}@github.com/matocool/mimotion.git](http://xunichanghuan:$%7Bgit_pwd%7D@github.com/matocool/mimotion.git)
> 为什么还用作者的用户名啊？这肯定不行啊。你的把rum里面全换成自己的才行。

也谢谢热心的哥们，目前搞定了。没有报错了，~

**Comment by zailushang2008** [comment]
我这也是这个问题，谁帮我看看。。。
Process completed with exit code 1.
