### ISSUE TITLE
刷步数大部分都是成功的，但是还是偶尔会有个别错误

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion#16]
这是作者自己的。。。。也会有错误。。。不知道这是为啥。。。。依旧code1

![image](https://user-images.githubusercontent.com/83129369/132369903-daf79c93-f367-4084-a879-2dda49b5eff6.png)

**Comment by kurtn2005** [comment]
这个可以忽略，毕竟免费的Github Action，还要啥自行车。

**Comment by matocool** [comment]
> 这个可以忽略，毕竟免费的Github Action，还要啥自行车。

好吧。。。我以为按道理应该都不会出错的

**Comment by hydjan** [comment]
> > 这个可以忽略，毕竟免费的Github Action，还要啥自行车。
> 
> 好吧。。。我以为按道理应该都不会出错的

看了一下代码，这个错误是因为重置刷新时间分钟数是0-9的随机数，如果这次随机的分钟数和上次相同，那么就出现“Your branch is up to date with 'origin/master'.nothing to commit, working tree clean“的错误提示，不影响运行，可以忽略，1/10的概率会出现这个错误提示。

**Comment by matocool** [comment]
> > > 这个可以忽略，毕竟免费的Github Action，还要啥自行车。
> > 
> > 
> > 好吧。。。我以为按道理应该都不会出错的
> 
> 看了一下代码，这个错误是因为重置刷新时间分钟数是0-9的随机数，如果这次随机的分钟数和上次相同，那么就出现“Your branch is up to date with 'origin/master'.nothing to commit, working tree clean“的错误提示，不影响运行，可以忽略，1/10的概率会出现这个错误提示。

原来如此，谢谢大佬
