### ISSUE TITLE
GIT_PWD  &    PAT  可否使用同一个令牌？

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion#19]
GIT_PWD 我给与了全部权限，

PAT只要部分权限。

GIT_PWD令牌的权限包含了PAT所需的权限。

那么我PAT直接使用GIT_PWD的令牌应该没毛病吧。

**Comment by xunichanghuan** [comment]
是同一个，用一个值就行，写代码的时候忘了合并

**Comment by xunichanghuan** [comment]
刚看了一下，GIT_PWD为旧代码变量，已无效，刚在README.md中做了删除，请重新同步代码
