### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by zailushang2008** [xunichanghuan/mimotion#31]
我那个企业微信的POSITION设置是：false，其他都是NO
通知只开启了server酱，其他通知都没开启
天气开启了。
作者这是啥问题呀？
https://github.com/zailushang2008/mimotion
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    getBeijinTime()
  File "main.py", line 164, in getBeijinTime
    run(msg_mi)
  File "main.py", line 344, in run
    req_urls = req_url + get_access_token()
  File "main.py", line 323, in get_access_token
    access_token = resp['access_token']
KeyError: 'access_token'
Error: Process completed with exit code 1.

**Comment by Geek-monk** [comment]
请问这个问题解决了吗

**Comment by PRSJMC** [comment]
类似的问题，所有通知设置都是关闭，报错如下：（虽然不影响步数修改）
`已设置为随机步数(30000~39999)
***
***
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    getBeijinTime()
  File "main.py", line 164, in getBeijinTime
    run(msg_mi)
  File "main.py", line 3[44](https://github.com/PRSJMC/mimotion/runs/5460831436?check_suite_focus=true#step:5:44), in run
    req_urls = req_url + get_access_token()
  File "main.py", line 323, in get_access_token
    access_token = resp['access_token']
KeyError: 'access_token'
Error: Process completed with exit code 1.`

**Comment by zailushang2008** [comment]
> 请问这个问题解决了吗

no solution yet

**Comment by zailushang2008** [comment]
> 

it's normal

**Comment by zailushang2008** [comment]
> 类似的问题，所有通知设置都是关闭，报错如下：（虽然不影响步数修改）
> 
> ```
> 已设置为随机步数(30000~39999)
> ***
> ***
> Traceback (most recent call last):
>   File "main.py", line 356, in <module>
>     getBeijinTime()
>   File "main.py", line 164, in getBeijinTime
>     run(msg_mi)
>   File "main.py", line 3[44](https://github.com/PRSJMC/mimotion/runs/5460831436?check_suite_focus=true#step:5:44), in run
>     req_urls = req_url + get_access_token()
>   File "main.py", line 323, in get_access_token
>     access_token = resp['access_token']
> KeyError: 'access_token'
> Error: Process completed with exit code 1.
> ```

静候有缘人

**Comment by zailushang2008** [comment]
> 类似的问题，所有通知设置都是关闭，报错如下：（虽然不影响步数修改）
> 
> ```
> 已设置为随机步数(30000~39999)
> ***
> ***
> Traceback (most recent call last):
>   File "main.py", line 356, in <module>
>     getBeijinTime()
>   File "main.py", line 164, in getBeijinTime
>     run(msg_mi)
>   File "main.py", line 3[44](https://github.com/PRSJMC/mimotion/runs/5460831436?check_suite_focus=true#step:5:44), in run
>     req_urls = req_url + get_access_token()
>   File "main.py", line 323, in get_access_token
>     access_token = resp['access_token']
> KeyError: 'access_token'
> Error: Process completed with exit code 1.
> ```

静候有缘人

**Comment by unclear1427** [comment]
有两种处理方式：
1.如 @Serendipity-Hzh的做法，可以在main.py文件内直接将position直接设置为False关闭，如果要用此功能则设置为True；
2.也可以将main.py文件内第328行的`    if position :`修改为`    if position != 'NO' :`，将设置Secrets变量的POSITION设置为`NO`即可，若需要开启可以设置为`YES`（事实上，只要不是NO就行）。

> > 类似的问题，所有通知设置都是关闭，报错如下：（虽然不影响步数修改）
> > ```
> > 已设置为随机步数(30000~39999)
> > ***
> > ***
> > Traceback (most recent call last):
> >   File "main.py", line 356, in <module>
> >     getBeijinTime()
> >   File "main.py", line 164, in getBeijinTime
> >     run(msg_mi)
> >   File "main.py", line 3[44](https://github.com/PRSJMC/mimotion/runs/5460831436?check_suite_focus=true#step:5:44), in run
> >     req_urls = req_url + get_access_token()
> >   File "main.py", line 323, in get_access_token
> >     access_token = resp['access_token']
> > KeyError: 'access_token'
> > Error: Process completed with exit code 1.
> > ```
> 
> 静候有缘人

**Comment by xunichanghuan** [comment]
已修复
