### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by Limyihong** [xunichanghuan/mimotion#47]
失效了

**Comment by dotama** [comment]
查看github action, 提示：This check was skipped

**Comment by dotama** [comment]
> 失效了

貌似注释 run.yml 17行可以
# if: github.event.repository.owner.id == github.event.sender.id

**Comment by Limyihong** [comment]
> > 失效了
> 
> 貌似注释 run.yml 17行可以 #if: github.event.repository.owner.id == github.event.sender.id

我注释了还是不行

**Comment by 0yykk** [comment]
> > > 失效了
> > 
> > 
> > 貌似注释 run.yml 17行可以 #if: github.event.repository.owner.id == github.event.sender.id
> 
> 我注释了还是不行

貌似是天气接口有问题，建议根据天气设置随机步数设置为False

**Comment by generaljun** [comment]
2022年09月30日，已经失效4天。

**Comment by matocool** [comment]
Error: Process completed with exit code 1.

**Comment by xunichanghuan** [comment]
已修复
