### ISSUE TITLE
KeyError: 'access_token'，，，这个报错。。。

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion#49]
![image](https://user-images.githubusercontent.com/83129369/193235495-6365a9ab-2fcf-41c5-8df7-1348b8139169.png)

![image](https://user-images.githubusercontent.com/83129369/193235549-fc7613aa-e19d-4ff3-befa-8c9f78a9acf0.png)

**Comment by matocool** [comment]
![image](https://user-images.githubusercontent.com/83129369/193239294-037b0151-51d8-4fdf-aa35-9b053c7bc5f8.png)

**Comment by licooi** [comment]
还是不行呀

**Comment by matocool** [comment]
> 还是不行呀

你是怎么修改的呢

**Comment by licooi** [comment]
按照你说的修改了。但是不同步数据

**Comment by matocool** [comment]
> 按照你说的修改了。但是不同步数据

action运行成功了？但是没有同步到支付宝？

**Comment by licooi** [comment]
对的，运营成功了，但没有同步到支付宝

**Comment by licooi** [comment]
刚开始会运行成功，后面任务也不执行了直接跳过……

**Comment by matocool** [comment]
> 刚开始会运行成功，后面任务也不执行了直接跳过……

我目前也是这种情况，为了修复，我删掉fork，重新fork并且填入有关机密。还是不行。
