### ISSUE TITLE
提个小建议，合并多帐号消息推送

### ISSUE THREAD

**Issue by kurtn2005** [xunichanghuan/mimotion#5]
感觉你的程序特别人性化，可以根据天气和时间段来酌情增加步数。

就是每次推送多账号时会有多条消息，我有3个帐号，每次都收到3条信息，能否设置个1条信息包含三个帐户的汇总呢？

当然多条推送也无所谓，只是个小建议。

**Comment by xunichanghuan** [comment]
多帐号消息推送已合并，请测试反馈

**Comment by kurtn2005** [comment]
> 多帐号消息推送已合并，请测试反馈

已测试4次定时推送，没问题。感谢！
