### ISSUE TITLE
终于搞定，从22号到今天，总算可以用了。。。。

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion#50]
之前什么都没动。。

突然好好地不能用了。。。。

然后，在下边↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
二、设置账号密码
添加名为 USER、PWD、SKEY、SCKEY、POSITION 、CORPID、CORPSECRET、AGENTID、TOUSER、TOPARTY、TOTAG、OPEN_GET_WEATHER、AREA的变量: Settings-->Secrets-->New secret
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

按照说明，改成如下。

OPEN_GET_WEATHER              False
AREA                                        NO
POSITION                                 false
CORPID                                    NO
CORPSECRET                            NO

然后点击星号，运行。虽然还有报错。但是支付宝里面步数变了。成功了。推荐试试。

**Comment by matocool** [comment]
虽然依然报错，但是成功了！！

![Screenshot_2022-09-30-17-27-57-320_com tencent we](https://user-images.githubusercontent.com/83129369/193239901-3266ec3d-a2d8-49fd-ab81-360ce85080af.jpg)
![Screenshot_2022-09-30-17-27-57-320_com tencent we](https://user-images.githubusercontent.com/83129369/193239932-9f38d5e6-41b3-4c5d-a1d9-7816ef3aaeb0.jpg)

**Comment by xunichanghuan** [comment]
已修复天气api
