### ISSUE TITLE
action 自动运行出问题？

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion#51]
自从十来天前，出错之后。前天自己修改好了。但是要自己手电点击star运行才可以。

然后我的运行时间，是默认设置。按道理早上8  10  点这样，他会自动运行，并且推送。。。

但是现在并不会自动运行了。。。。。。。。。。

手动运行的话，因为不在时间上，会提示：当前不是主人设定的提交步数时间或者主人设置了0步数呢，本次不提交

大佬能不能改为，在凌晨4点至晚上22点之间随机生成两三个时间戳来提交，而不是按到整点才提交。

因为出现了问题，我无法解决搞定。

于是又过了几天，我把整个fork删除，重新fork。并且按要求填入机密，都是正确的。。

特意检查了，自定义启动时间。跟作者的一模一样。

但是作者的action我看了下会自动运行，而且是按照设置好的时间运行。然而自己的却不会自动运行。只能到了时间之后手动运行。

一直搞不懂 问题出在哪里。

在设定的时间，手动运行，刷步数并且提交到支付宝是可以成功的。说明代码那些应该都没问题，就是死活无法自动运行。

希望作者大大可以看一下谢谢

https://github.com/matocool/mimotion/actions

明明代码一样，启动时间一样。我的就是无法运行，而作者的却可以。 谢谢

![image](https://user-images.githubusercontent.com/83129369/194024658-8f308ba5-48da-4d84-bb1b-beced5c725e3.png)

![1`9_X08CNNUDNS H%URSZNY](https://user-images.githubusercontent.com/83129369/193808094-4d65e5c0-f04f-4c45-b895-27dfdc55bfde.png)

**Comment by matocool** [comment]
真是奇了怪了，前几天，我整个fork删除，重新fork。
并且按要求填入机密，都是正确的。。

特意检查了，自定义启动时间。跟作者的一模一样。

但是作者的action我看了下会自动运行。然而自己的却不会自动运行。只能到了时间之后手动运行。

一直搞不懂 问题出在哪里。

**Comment by matocool** [comment]
手动运行结果是可以出来的。说明代码那些应该都没问题，就是死活无法自动运行。

希望作者大大可以看一下谢谢

https://github.com/matocool/mimotion/actions

**Comment by xcyll** [comment]
https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml
删掉10，11，17行
不知发生了什么，大概8天前定时任务会被阻止执行，移除掉，并且同步移除掉star事件试试

**Comment by xcyll** [comment]
https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml
删掉10，11，17行
不知发生了什么，大概8天前定时任务会被阻止执行（涉及到所有ation定时任务？我看了别的一些项目也是这样，定时任务被skiped了---This job was skipped---）
移除掉17行，并且同步移除掉star事件试试

**Comment by xcyll** [comment]
https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml
删掉10，11，17行
不知何故，大概8天前定时任务就被阻止执行了（涉及到所有ation定时任务？我看了别的一些项目也是这样，定时任务被skiped了---This job was skipped---）
移除掉17行，并且同步移除掉star事件试试

**Comment by xcyll** [comment]
https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml
删掉10，11，17行
不知何故，大概8天前定时任务就被阻止执行了（涉及到所有ation定时任务？我看了别的一些项目也是这样，定时任务被skiped了---提示This job was skipped---）
移除掉17行，并且同步移除掉star事件试试

**Comment by xcyll** [comment]
看了下作者的刷步数定时任务好像也是失败的
eg：刷步数任务#3229: Scheduled 任务3229自动执行时间10月5日

**Comment by matocool** [comment]
> 

谢谢老哥分享我试试。


但是作者的其余时间都是正常的。按道理。我在别的触发时间点应该也要自动执行的。可是偏偏不执行。

**Comment by matocool** [comment]
Manually run by [xunichanghuan](https://github.com/xunichanghuan)      作者的触发好像也都是手动触发？

![image](https://user-images.githubusercontent.com/83129369/194442289-9792de21-6cdc-4a03-9791-abc5a92756b5.png)

我自己的触发全被跳过...
![image](https://user-images.githubusercontent.com/83129369/194442363-537b977f-8188-465c-acbc-cda6f1bbfd77.png)

**Comment by matocool** [comment]
> 看了下作者的刷步数定时任务好像也是失败的 eg：刷步数任务#3229: Scheduled 任务3229自动执行时间10月5日

https://github.com/xunichanghuan/mimotion/actions/runs/3190027394         3229还是成功的了

**Comment by xcyll** [comment]
嗯嗯 手动触发没问题
出问题的是Scheduled任务

**Comment by xcyll** [comment]
![22-10-07 084043](https://user-images.githubusercontent.com/63227888/194442676-3e9228e4-1846-4701-bc41-2f22a4cc2bf5.png)
右下角标签

**Comment by xcyll** [comment]
Scheduled

**Comment by xcyll** [comment]
涉及的是Scheduled任务

**Comment by matocool** [comment]
> 涉及的是Scheduled任务
老哥你看看我这样可以吗


![image](https://user-images.githubusercontent.com/83129369/194443652-f62ec310-286a-4647-9965-99efd5dcb3c7.png)

**Comment by xcyll** [comment]
应该可以的
9行加个utc 1点时间 看看过会儿执不执行

**Comment by matocool** [comment]
> 应该可以的

谢谢大佬，我这边等待带时间看下效果。刚刚手动测试没出毛病。

顺便请教下

https://github.com/xunichanghuan/mimotion/blob/master/random_cron.sh

20行，21行，

20行：if [[ ( $(date '+%H') == 00 ) || ( $(date '+%H') == 03 )  || ( $(date '+%H') == 05 )

21行：time=$(($RANDOM%10))" 0,2,5,7,9,11,13 * * *"

他这边似乎有个时间对不上，00 03  05  ，下面是 0257.....

那么20行date '+%H') == 03 要改为 date '+%H') == 02 吗？

谢谢

**Comment by matocool** [comment]
> 应该可以的

2022年10月7日 10:17:45

刚刚看了下不行。。。作者的运行成功了。。。

**Comment by xcyll** [comment]
俺不是大佬哈😂
看了下你的Scheduled任务能运行了啊

**Comment by xcyll** [comment]
![22-10-07 084043](https://user-images.githubusercontent.com/63227888/194485483-0e758533-a3ac-456d-9142-a4449b48e82d.png)

**Comment by xcyll** [comment]
> > 应该可以的
> 
> 2022年10月7日 10:17:45
> 
> 刚刚看了下不行。。。作者的运行成功了。。。

![10-07 150213](https://user-images.githubusercontent.com/63227888/194487669-8c600721-61dc-48e5-b162-4fe0364888f0.png)
作者的Scheduled的任务 ; on:watch任务 也是被skip的

**Comment by matocool** [comment]
> ![22-10-07 084043](https://user-images.githubusercontent.com/63227888/194485483-0e758533-a3ac-456d-9142-a4449b48e82d.png)

是啊。。。。前面按你说的修改，第一次还是失败的。。。。不懂怎么滴，突然又好了。。。这个应该是action出大问题了

**Comment by xcyll** [comment]
> > 应该可以的
> 
> 2022年10月7日 10:17:45
> 
> 刚刚看了下不行。。。作者的运行成功了。。。

第一次失败是指哪个标签任务
同时段作者的成功了？他的是哪个标签

**Comment by xcyll** [comment]
> > 应该可以的
> 
> 2022年10月7日 10:17:45
> 
> 刚刚看了下不行。。。作者的运行成功了。。。

![IMG_0220](https://user-images.githubusercontent.com/63227888/194680201-64dd4e60-dc1b-4c6c-ad32-d2c14f6609b2.jpg)
看了下作者的Scheduled标签任务没运行成功的,最近一次仍是被skip
你修改后第一次Scheduled标签任务是：【刷步数 #37: Scheduled]】是运行成功的  上一次的是没修改之前的【刷步数 #32: Scheduled被skiped了】
第二次Scheduled标签任务【刷步数 #38: Scheduled】也是在运行的没有被skip 出现Error: The operation was canceled可能是你手动取消的

**Comment by xcyll** [comment]
你修改后第一次是 刷步数 #37: Scheduled，后续都没有被skiped
![IMG_021](https://user-images.githubusercontent.com/63227888/194681022-d87c63fb-377a-4ac9-a121-c85556689731.jpg)

**Comment by matocool** [comment]
> > > 应该可以的
> > 
> > 
> > 2022年10月7日 10:17:45
> > 刚刚看了下不行。。。作者的运行成功了。。。
> 
> ![IMG_0220](https://user-images.githubusercontent.com/63227888/194680201-64dd4e60-dc1b-4c6c-ad32-d2c14f6609b2.jpg) 看了下作者的Scheduled标签任务没运行成功的,最近一次仍是被skip 你修改后第一次Scheduled标签任务是：【刷步数 #37: Scheduled]】是运行成功的 上一次的是没修改之前的【刷步数 #32: Scheduled被skiped了】 第二次Scheduled标签任务【刷步数 #38: Scheduled】也是在运行的没有被skip 出现Error: The operation was canceled可能是你手动取消的

感谢大佬~已经搞定，就是运行时间跟设置的不一样。。。但是可以成功刷上了。。。

**Comment by matocool** [comment]
> 你修改后第一次Scheduled标签任务【自动运行的】是 刷步数 #37: Scheduled，后续都没有被skiped ![IMG_021](https://user-images.githubusercontent.com/63227888/194681022-d87c63fb-377a-4ac9-a121-c85556689731.jpg)

根据作者的说明如下：


四、自定义启动时间

编辑 main.py

找到 time_list项目，此数据为北京时间，默认表示为8点10点13点15点17点19点21点运行,如需修改，请修改time_list列表，
如：time_list = [7, 9, 13, 15, 17, 19, 20]就表示为7点9点13点15点17点19点20点运行，Actions触发里面也要同步修改。 
编辑 random_cron.sh 修改其中if语句的判断时间为UTC时间，即北京时间-8，如北京时间8点为UTC时间0点，需要运行的时间-8就是UTC时间



然后本人仔细对比自己跟作者的文件如下：
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
https://github.com/xunichanghuan/mimotion/blob/master/random_cron.sh
https://github.com/matocool/mimotion/blob/master/random_cron.sh


https://github.com/xunichanghuan/mimotion/blob/master/main.py
https://github.com/matocool/mimotion/blob/master/main.py


time_list = [8, 10, 13, 15, 17, 19, 21]


if [[ ( $(date '+%H') == 00 ) || ( $(date '+%H') == 03 )  || ( $(date '+%H') == 05 )  || ( $(date '+%H') == 07 )  || ( $(date '+%H') == 09 )  || ( $(date '+%H') == 11 )  || ( $(date '+%H') == 13 ) ]] ;then

time=$(($RANDOM%10))" 0,2,5,7,9,11,13 * * *"

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
在启动时间方面，对比作者的设置之后发现一模一样，没有区别，

但是实际上在任务运行时间上有区别。

这是我的：

#46     Sat, 08 Oct 2022 09:19:51 GMT         17:19:51        已设置为随机步数(40000~49999)

#45     Sat, 08 Oct 2022 07:30:58 GMT         15:30:58        已设置为随机步数(30000~39999)

#44     Sat, 08 Oct 2022 05:42:55 GMT         13:42:55        已设置为随机步数(20000~29999)

#43     Sat, 08 Oct 2022 03:42:25 GMT         11:42:25        当前不是主人设定的提交步数时间或者主人设置了0步数呢，本次不提交	

#42     Sat, 08 Oct 2022 01:25:59 GMT         09:25:59        当前不是主人设定的提交步数时间或者主人设置了0步数呢，本次不提交

#41     Fri, 07 Oct 2022 14:06:34 GMT          22:06:34        当前不是主人设定的提交步数时间或者主人设置了0步数呢，本次不提交




这是作者的：


#3262    Sat, 08 Oct 2022 09:10:52 GMT       17:10:52            已设置为随机步数(36000~44999)

#3260    Sat, 08 Oct 2022 07:10:49 GMT       15:10:49            已设置为随机步数(24000~31999)

#3259    Sat, 08 Oct 2022 05:10:48 GMT       13:10:48            已设置为随机步数(14000~20999)

#3258    Sat, 08 Oct 2022 02:10:50 GMT       10:10:50            已设置为随机步数(7000~13999)

#3257    Sat, 08 Oct 2022 00:10:48 GMT       08:10:48            已设置为随机步数(4800~7999)

#3255    Fri, 07 Oct 2022 13:10:51 GMT        21:10:51            已设置为随机步数(60000~69999)	



可以发现作者的运行时间节点均按照time_list = [8, 10, 13, 15, 17, 19, 21]运行

而我自己的运行时间点在 8点 10点 均未运行，运行时间推迟了90分钟///参考 #43 #42


最奇怪的问题就是，为什么设置一模一样，作者却可以按时间运行，我却不可以。作者的延迟基本在10分钟左右。我的延迟范围在20~100反正....action虽然有延迟，但是也没这么夸张吧。




从#42 开始，提示如下

Annotations
1 warning
build
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, actions/setup-python, actions/checkout


注释

1个警告

建筑

节点。js 12操作已弃用。有关详细信息，请参见：https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.请更新以下操作以使用节点。js 16:actions/checkout、actions/setup-python、action/setup-pythin、actions/checkout

**Comment by matocool** [comment]
https://github.com/xunichanghuan/mimotion/actions/workflows/run.yml

又看了一眼。。。。

作者的Scheduled全部是跳过的

运行成功的 全部是  Manually run by [xunichanghuan](https://github.com/xunichanghuan)


不懂作者是怎么做到模拟Manually  run 的

**Comment by whyalwaysmea** [comment]
@matocool 请问是哪里的问题导致action 自动运行出问题的呢，应该如何解决啊？

**Comment by matocool** [comment]
> 

根据大佬给出的提示

[xcyll](https://github.com/xcyll) commented [6 days ago](https://github.com/xunichanghuan/mimotion/issues/51#issuecomment-1268679808)
https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml
删掉10，11，17行
不知何故，大概8天前定时任务就被阻止执行了（涉及到所有ation定时任务？我看了别的一些项目也是这样，定时任务被skiped了---提示This job was skipped---）
移除掉17行，并且同步移除掉star事件试试

-----------------------------------------------------------------------------------------------------------------

我是按照这个大佬的提示成功的。。。。

这个action应该是自己的问题。。。现在的action延迟比较严重，我这边延迟基本要60分钟左右才会运行。比如你设置北京时间8点，实际上基本要8.50~9.30 之间才会运行。不过影响不大。毕竟终究是运行了。

你可以直接fork我弄好的，我看了下你fork的是另外个，那个没有推送感觉不好用。

其次，现在就算修改好，大概也要等待12~24 甚至 24~48 小时的时间。才会变得正常。


步骤如下：

1、fork https://github.com/matocool/mimotion
2、填入自己的机密
3、点击 star 或者 workflows
4、等待12~48小时，期间什么都不用管，他就会自动运行了。有推送的话，就知道了。

**Comment by licooi** [comment]
你好，fork你的库以后，把机密填完后就不需要去动它了嘛？

**Comment by licooi** [comment]
> 根据大佬给出的提示
> 
> [xcyll](https://github.com/xcyll) commented [6 days ago](https://github.com/xunichanghuan/mimotion/issues/51#issuecomment-1268679808) https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml 删掉10，11，17行 不知何故，大概8天前定时任务就被阻止执行了（涉及到所有ation定时任务？我看了别的一些项目也是这样，定时任务被skiped了---提示This job was skipped---） 移除掉17行，并且同步移除掉star事件试试
> 
> 我是按照这个大佬的提示成功的。。。。
> 
> 这个action应该是自己的问题。。。现在的action延迟比较严重，我这边延迟基本要60分钟左右才会运行。比如你设置北京时间8点，实际上基本要8.50~9.30 之间才会运行。不过影响不大。毕竟终究是运行了。
> 
> 你可以直接fork我弄好的，我看了下你fork的是另外个，那个没有推送感觉不好用。
> 
> 其次，现在就算修改好，大概也要等待12~24 甚至 24~48 小时的时间。才会变得正常。
> 
> 步骤如下：
> 
> 1、fork https://github.com/matocool/mimotion 2、填入自己的机密 3、点击 star 或者 workflows 4、等待12~48小时，期间什么都不用管，他就会自动运行了。有推送的话，就知道了。

**Comment by licooi** [comment]
你好，fork你的库以后把机密输入后，只需要等待就可以了嘛？

**Comment by matocool** [comment]
> 你好，fork你的库以后把机密输入后，只需要等待就可以了嘛？

是的，大概24小时即可

**Comment by matocool** [comment]
> 你好，fork你的库以后把机密输入后，只需要等待就可以了嘛？

我看了下你的action，，你删掉你复制的，重新FORK一次，再填入机密。

**Comment by matocool** [comment]
> 你好，fork你的库以后把机密输入后，只需要等待就可以了嘛？

你不填入机密吗？

https://github.com/licooi/mimotion-spare-version/actions/workflows/run.yml

打开这个链接，让他运行啊。。

**Comment by licooi** [comment]
我填入了呀

**Comment by licooi** [comment]
![Uploading C1A4233B-BBF3-415E-ABEA-DC27389FB301.png…]()

**Comment by matocool** [comment]
> 我填入了呀

嗯。。我看你fork好几次。。。然后看了下action都没动。。。以为你弄错了。。。

现在没事了。。

**Comment by mbsfc** [comment]
首次运行失败,提示这个,机密都输入了.

Traceback (most recent call last):
  File "main.py", line 28, in <module>
    open_get_weather = sys.argv[12]
IndexError: list index out of range
Error: Process completed with exit code 1.

**Comment by VoxHwa** [comment]
> > 
> 
> 根据大佬给出的提示
> 
> [xcyll](https://github.com/xcyll) commented [6 days ago](https://github.com/xunichanghuan/mimotion/issues/51#issuecomment-1268679808) https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml 删掉10，11，17行 不知何故，大概8天前定时任务就被阻止执行了（涉及到所有ation定时任务？我看了别的一些项目也是这样，定时任务被skiped了---提示This job was skipped---） 移除掉17行，并且同步移除掉star事件试试
> 
> 我是按照这个大佬的提示成功的。。。。
> 
> 这个action应该是自己的问题。。。现在的action延迟比较严重，我这边延迟基本要60分钟左右才会运行。比如你设置北京时间8点，实际上基本要8.50~9.30 之间才会运行。不过影响不大。毕竟终究是运行了。
> 
> 你可以直接fork我弄好的，我看了下你fork的是另外个，那个没有推送感觉不好用。
> 
> 其次，现在就算修改好，大概也要等待12~24 甚至 24~48 小时的时间。才会变得正常。
> 
> 步骤如下：
> 
> 1、fork https://github.com/matocool/mimotion-spare-version 2、填入自己的机密 3、点击 star 或者 workflows 4、等待12~48小时，期间什么都不用管，他就会自动运行了。有推送的话，就知道了。

如果直接点run workflow（manually run)影响schedule的自动run嘛

**Comment by matocool** [comment]
> > > 
> > 
> > 
> > 根据大佬给出的提示
> > [xcyll](https://github.com/xcyll) commented [6 days ago](https://github.com/xunichanghuan/mimotion/issues/51#issuecomment-1268679808) https://github.com/matocool/mimotion/blob/master/.github/workflows/run.yml 删掉10，11，17行 不知何故，大概8天前定时任务就被阻止执行了（涉及到所有ation定时任务？我看了别的一些项目也是这样，定时任务被skiped了---提示This job was skipped---） 移除掉17行，并且同步移除掉star事件试试
> > 我是按照这个大佬的提示成功的。。。。
> > 这个action应该是自己的问题。。。现在的action延迟比较严重，我这边延迟基本要60分钟左右才会运行。比如你设置北京时间8点，实际上基本要8.50~9.30 之间才会运行。不过影响不大。毕竟终究是运行了。
> > 你可以直接fork我弄好的，我看了下你fork的是另外个，那个没有推送感觉不好用。
> > 其次，现在就算修改好，大概也要等待12~24 甚至 24~48 小时的时间。才会变得正常。
> > 步骤如下：
> > 1、fork https://github.com/matocool/mimotion-spare-version 2、填入自己的机密 3、点击 star 或者 workflows 4、等待12~48小时，期间什么都不用管，他就会自动运行了。有推送的话，就知道了。
> 
> 如果直接点run workflow（manually run)影响schedule的自动run嘛

不会啊。。。一次就好

**Comment by licooi** [comment]
@matocool 
昨天开始又提示
Error: Process completed with exit code 1.

运行失败
