### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion#57]
(https://github.com/xunichanghuan/mimotion/actions/runs/3233440777)

Annotations
1 warning

buildNode.js 12 actions are deprecated.

 For more information see:

 https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 

Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, actions/setup-python, actions/checkout
--

**Comment by VoxHwa** [comment]
同样的问题

**Comment by wearehere8** [comment]
把这些更改到最新版就好了
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version: '3.10'
