### ISSUE TITLE
重置时间报错是什么问题呢

### ISSUE THREAD

**Issue by chaoqiangwang** [xunichanghuan/mimotion#8]
remote: Permission to xunichanghuan/mimotion.git denied to chaoqiangwang.
fatal: unable to access 'http://github.com/xunichanghuan/mimotion.git/': The requested URL returned error: 403
Error: Process completed with exit code 128

**Comment by kurtn2005** [comment]
> remote: Permission to xunichanghuan/mimotion.git denied to chaoqiangwang.
> fatal: unable to access '[http://github.com/xunichanghuan/mimotion.git/](https://github.com/xunichanghuan/mimotion.git/)': The requested URL returned error: 403
> Error: Process completed with exit code 128

不要用作者的git地址，用你自己的。
